name: pay_digitalwallets_sdk
description: Olo Digital Wallets Flutter Plugin
version: 1.0.0
homepage: "https://www.olo.com"
repository: "https://github.com/ololabs/pay-digitalwallets-flutter-sdk-releases"

environment:
  sdk: ^3.5.0
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: pay_digitalwallets_sdk_android
      ios:
        default_package: pay_digitalwallets_sdk_ios

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0
  pay_digitalwallets_sdk_platform_interface: ^1.0.0
  pay_digitalwallets_sdk_android: ^1.0.0
  pay_digitalwallets_sdk_ios: ^1.0.0

dependency_overrides:
  pay_digitalwallets_sdk_android:
    path: ../pay_digitalwallets_sdk_android
  pay_digitalwallets_sdk_ios:
    path: ../pay_digitalwallets_sdk_ios
  pay_digitalwallets_sdk_platform_interface:
    path: ../pay_digitalwallets_sdk_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  plugin_platform_interface: ^2.1.8
