name: pay_digitalwallets_sdk_example
description: Demonstrates how to use the pay_digitalwallets_sdk plugin.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  pay_digitalwallets_sdk:
    # When depending on this package from a real application you should use:
    #   pay_digitalwallets_sdk: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

dependency_overrides:
  pay_digitalwallets_sdk_android:
    path: ../../pay_digitalwallets_sdk_android
  pay_digitalwallets_sdk_ios:
    path: ../../pay_digitalwallets_sdk_ios
  pay_digitalwallets_sdk_platform_interface:
    path: ../../pay_digitalwallets_sdk_platform_interface

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
