name: pay_digitalwallets_sdk_platform_interface
description: A common platform interface for the pay_digitalwallets_sdk plugin.
version: 1.0.0
homepage: "https://www.olo.com"
repository: "https://github.com/ololabs/pay-digitalwallets-flutter-sdk-releases"

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
