name: pay_digitalwallets_sdk_ios
description: iOS implementation of the pay_digitalwallets_sdk plugin
version: 1.0.0
homepage: "https://www.olo.com"
repository: "https://github.com/ololabs/pay-digitalwallets-flutter-sdk-releases"

environment:
  sdk: ^3.5.0
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: pay_digitalwallets_sdk
    platforms:
      ios:
        package: pay_digitalwallets_sdk_ios
        pluginClass: PayDigitalWalletsSdkPlugin
        dartPluginClass: PayDigitalWalletsSdkIOS

dependencies:
  flutter:
    sdk: flutter
  pay_digitalwallets_sdk_platform_interface: ^1.0.0

dependency_overrides: 
  pay_digitalwallets_sdk_platform_interface:
    path: ../pay_digitalwallets_sdk_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
